### ISSUE TITLE
AttributeError: /lib/libportaudio.so: undefined symbol: Pa_GetVersionText

### ISSUE THREAD

**Issue by sp00ck** [romanz/amodem#56]
last ubuntu on raspbery pi (all version)
----
```
$echo "p" | amodem send
Audio OFDM MODEM v1.15.3: 48.0 kb/s (64-QAM x 8 carriers) Fs=32.0 kHz
Traceback (most recent call last):
  File "/home/userek/.local/bin/amodem", line 8, in <module>
    sys.exit(_main())
  File "/home/userek/.local/lib/python3.9/site-packages/amodem/__main__.py", line 248, in _main
    interface.load(args.audio_library)
  File "/home/userek/.local/lib/python3.9/site-packages/amodem/audio.py", line 20, in load
    version = self.call('GetVersionText', restype=ctypes.c_char_p)
  File "/home/userek/.local/lib/python3.9/site-packages/amodem/audio.py", line 32, in call
    func = getattr(self.lib, func_name)
  File "/usr/lib/python3.9/ctypes/__init__.py", line 387, in __getattr__
    func = self.__getitem__(name)
  File "/usr/lib/python3.9/ctypes/__init__.py", line 392, in __getitem__
    func = self._FuncPtr((name_or_ordinal, self))
AttributeError: /lib/libportaudio.so: undefined symbol: Pa_GetVersionText

```
$ python --version
Python 3.9.2

**Comment by ke4ahr** [comment]
Can you reproduce this by using an input file like the example shows? It's possible that the program doesn't handle data below a certain size. You may be able to fix this by zero-padding the input data.
