### ISSUE TITLE
Implicit dependency on setuptools(No module named 'pkg_resources')

### ISSUE THREAD

**Issue by AmeyaVS** [romanz/amodem#76]
Hello,

While trying out the project on my system in a virtual env.
I am encountering following error:

```
Traceback (most recent call last):
  File "/home/ameya/venvs/bin/amodem", line 5, in <module>
    from amodem.__main__ import _main
  File "/home/ameya/venvs/lib/python3.12/site-packages/amodem/__main__.py", line 9, in <module>
    import pkg_resources
ModuleNotFoundError: No module named 'pkg_resources'
```
The issue disappears after installing the following package in the virtualenv:
```
pip install setuptools
```

**Comment by AmeyaVS** [comment]
I also see that the PR #67 updates the `setuptools` dependency in the CI.
But it also needs to be added to the `setup.py` for the dependency when trying to install the tool using pip.

**Comment by y2k04** [comment]
pkg_resources has been marked for deprecation.
```
C:\Users\...\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.13_qbz5n2kfra8p0\LocalCache\local-packages\Python313\site-packages\amodem\__main__.py:10:
UserWarning: pkg_resources is deprecated as an API. See https://setuptools.pypa.io/en/latest/pkg_resources.html.
The pkg_resources package is slated for removal as early as 2025-11-30.
Refrain from using this package or pin to Setuptools<81.
  import pkg_resources
```

**Comment by enzanumo** [comment]
Experiencing same issue. My fix: 
1. remove import pkg_resources
2. modify this function: 
```
def _version():
    from importlib.metadata import version
    return (version("amodem"))
```
